# Generated by Django 4.0.2 on 2022-03-01 08:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend_name', models.CharField(max_length=50)),
                ('legend_short_story', models.TextField()),
                ('legend_roles', models.CharField(max_length=50)),
                ('legend_inspiring', models.CharField(max_length=100)),
                ('legend_quotes', models.CharField(max_length=50)),
                ('legend_image', models.ImageField(default='coach.png', upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Legend_story',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Live_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_score', models.PositiveIntegerField(default=0)),
                ('team2_score', models.PositiveIntegerField(default=0)),
                ('match_link', models.URLField()),
                ('date', models.DateTimeField()),
                ('suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Live_match',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_number', models.PositiveIntegerField()),
                ('player_position', models.CharField(choices=[('striker', 'striker'), ('goalkeeper', 'goalkeeper'), ('left_winger', 'left_winger'), ('right_winger', 'right_winger'), ('fullback', 'fullback'), ('wingback', 'wingback'), ('centre_back', 'centre_back'), ('attacking_midfielder', 'attacking_midfielder'), ('defensive_midfielder', 'defensive_midfielder'), ('centre_midfielder', 'centre_midfielder')], max_length=200)),
                ('player_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Player',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ranking_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_year', models.DateField()),
                ('ranking_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ranking_year',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_picture', models.ImageField(default='team_logo.png', upload_to='images/')),
                ('team_president', models.CharField(max_length=100)),
                ('player', models.ManyToManyField(to='team.Player')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_name', models.CharField(max_length=100)),
                ('trophy_year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Trophy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Trophy_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_number', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
                ('trophy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.trophy')),
            ],
            options={
                'verbose_name_plural': 'Trophy',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Team_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('team_location', models.CharField(blank=True, max_length=100, null=True)),
                ('team_founded', models.DateTimeField(blank=True, null=True)),
                ('team_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('team_link', models.URLField(blank=True, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Team_profile',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Table_Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('draw', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('loss', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('team_points', models.PositiveIntegerField(blank=True, null=True)),
                ('game_played', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ranking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.ranking_table')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Table_Ranking',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='player_statistics_ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_goals', models.PositiveIntegerField(default=0)),
                ('player_assist', models.PositiveIntegerField(default=0)),
                ('player_statistics', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.player')),
                ('player_year_statistics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.ranking_table')),
            ],
            options={
                'verbose_name_plural': 'player_statistics_Ranking',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Player_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_height', models.CharField(blank=True, max_length=50, null=True)),
                ('player_born', models.DateTimeField(blank=True, default=datetime.date(2022, 3, 1), null=True)),
                ('player_age', models.CharField(blank=True, max_length=100, null=True)),
                ('player_contact', models.EmailField(blank=True, max_length=100, null=True)),
                ('player_link', models.URLField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'verbose_name_plural': 'Player_profile',
                'ordering': ['-id'],
            },
        ),
    ]
