# Generated by Django 4.0.2 on 2022-03-01 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_statistics_ranking',
            name='player_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
        migrations.AlterField(
            model_name='player_statistics_ranking',
            name='player_statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.player'),
        ),
    ]
