# Generated by Django 4.0.2 on 2022-03-02 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_trophy_team_trophy_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy_team',
            name='trophy_number',
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_born',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 3), null=True),
        ),
    ]
