# Generated by Django 4.0.2 on 2022-03-08 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_trophy_team_trophy_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranking_table',
            options={'ordering': ['-ranking_year'], 'verbose_name_plural': 'Ranking_year'},
        ),
        migrations.AlterModelOptions(
            name='table_ranking',
            options={'ordering': ['-team_points'], 'verbose_name_plural': 'Table_Ranking'},
        ),
        migrations.AlterModelOptions(
            name='trophy_team',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Trophy Team'},
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_born',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 8), null=True),
        ),
    ]
