# Generated by Django 4.0.2 on 2022-03-09 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_ranking_table_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('manager_image', models.ImageField(upload_to='images/')),
                ('managers_formation', models.CharField(choices=[('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-2-2-2', '4-2-2-2'), ('4-4-2', '4-4-2'), ('3-4-3', '3-4-3'), ('3-4-2-1', '3-4-2-1'), ('3-5-2', '3-5-2')], max_length=20)),
                ('managers_birth_date', models.DateField(default=datetime.date(2022, 3, 9))),
                ('manager_age', models.IntegerField()),
                ('manager_country', models.CharField(max_length=30)),
                ('manager_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='player_statistics_ranking',
            options={'verbose_name_plural': 'player_statistics_Ranking'},
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_born',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 9), null=True),
        ),
    ]
