# Generated by Django 4.0.2 on 2022-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_club_managers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend_story',
            name='legend_inspiring',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legend_story',
            name='legend_quotes',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legend_story',
            name='legend_roles',
            field=models.CharField(max_length=250),
        ),
    ]
