# Generated by Django 4.0.2 on 2022-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_live_match_team1_logo_live_match_team2_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_match',
            name='match_type',
            field=models.CharField(default='PRIMUS PREMIER LEAGUE', max_length=50),
        ),
    ]
