# Generated by Django 4.0.2 on 2022-03-13 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_live_match_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_managers',
            name='managers_birth_date',
            field=models.DateField(default=datetime.date(2022, 3, 13)),
        ),
        migrations.AlterField(
            model_name='club_managers',
            name='managers_formation',
            field=models.CharField(choices=[('4-3-3', '4-3-3'), ('4-2-3-1', '4-2-3-1'), ('4-2-1-3', '4-2-1-3'), ('4-2-2-2', '4-2-2-2'), ('4-4-2', '4-4-2'), ('3-4-3', '3-4-3'), ('3-4-2-1', '3-4-2-1'), ('3-5-2', '3-5-2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_born',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 13), null=True),
        ),
    ]
