# Generated by Django 4.0.2 on 2022-03-14 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_club_managers_managers_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_managers',
            name='managers_birth_date',
            field=models.DateField(default=datetime.date(2022, 3, 15)),
        ),
        migrations.AlterField(
            model_name='player_profile',
            name='player_born',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 15), null=True),
        ),
    ]
