# Generated by Django 4.0.2 on 2022-03-15 11:06

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_club_managers_managers_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 15, 11, 6, 59, 251800, tzinfo=utc))),
                ('readed_message', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
            options={
                'verbose_name_plural': 'Connect Message',
                'ordering': ['-date'],
            },
        ),
    ]
