# Generated by Django 4.0.2 on 2022-03-15 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_connect_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 11, 16, 19, 799770, tzinfo=utc)),
        ),
    ]
