# Generated by Django 4.0.2 on 2022-03-29 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_team_team_email_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect_message',
            name='connect_file',
            field=models.FileField(default='answer.pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 13, 1, 17, 236205, tzinfo=utc)),
        ),
    ]
