# Generated by Django 4.0.2 on 2022-05-12 10:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_club_managers_current_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_managers',
            name='current_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.ranking_table'),
        ),
        migrations.AlterField(
            model_name='club_managers',
            name='current_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 36, 20, 562318, tzinfo=utc)),
        ),
    ]
