# Generated by Django 4.0.2 on 2022-05-12 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_trophy_manager_alter_connect_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club_managers',
            name='manager_trophy',
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 55, 46, 977692, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Trophy_manager',
        ),
    ]
