# Generated by Django 4.0.2 on 2022-05-12 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_remove_club_managers_manager_trophy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='trophy_image',
            field=models.ImageField(default='trophy.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 56, 45, 605320, tzinfo=utc)),
        ),
    ]
