# Generated by Django 4.0.2 on 2022-05-12 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_trophy_trophy_image_alter_connect_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_managers',
            name='manager_trophy',
            field=models.ManyToManyField(to='team.Trophy'),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 10, 57, 29, 514077, tzinfo=utc)),
        ),
    ]
