# Generated by Django 4.0.2 on 2022-05-13 11:35

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_alter_club_managers_manager_trophy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_managers',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 11, 35, 20, 384084, tzinfo=utc)),
        ),
    ]
