# Generated by Django 4.0.2 on 2022-05-13 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_club_managers_date_time_alter_connect_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='connect_message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 15, 1, 2, 323136, tzinfo=utc)),
        ),
    ]
